# -*- mode: python ; coding: utf-8 -*-
block_cipher = None

a = Analysis(['bibiocr.py'],
     pathex=[],
     binaries=[],
     datas=[('ppocr','ppocr'),
            ('cnocr_lite_onnx/cnocr','cnocr_lite_onnx/cnocr'),
            ('rapid_ocr/models/*.onnx','rapid_ocr/models'),
            ('rapid_ocr/ch_ppocr_server_v2_rec/*.txt','rapid_ocr/ch_ppocr_server_v2_rec'),
            ('*.json','.'),
            ('*.png','.'),
            ('*.ico','.')],
     hiddenimports=[ 'skimage',
                     'skimage.filters.edges',
                     'framework_pb2',
                     'pyqt5',
                     'pyqt5-tools',
                     'shapely',
                     'pyclipper',
                     'onnxruntime',
                     'Pillow',
                     'imgaug',
                     'imageio',
                     'skimage.transform',
                     'skimage.segmentation',
                     'scipy.cluster',
                     'scipy._lib._disjoint_set',
                     'lmdb',
                     'mainwindow'],
     hookspath=['.'],
     runtime_hooks=[],
     excludes=['matplotlib'],
     win_no_prefer_redirects=False,
     win_private_assemblies=False,
     cipher=block_cipher,
     noarchive=False)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(pyz,
     a.scripts,
     [],
     exclude_binaries=True,
     name='bibiocr',
     debug=False,
     bootloader_ignore_signals=False,
     strip=False,
     upx=True,
     console=True,
     console=False,
     icon='qtocr.ico')

coll = COLLECT(exe,
     a.binaries,
     a.zipfiles,
     a.datas,
     strip=False,
     upx=True,
     upx_exclude=[],
     name='bibiocr')